CREATE TABLE "lessons" (
	"id" text PRIMARY KEY NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"stage" integer NOT NULL,
	"skill" text NOT NULL,
	"difficulty" integer NOT NULL,
	"estimated_minutes" integer NOT NULL,
	"prerequisites" jsonb DEFAULT '[]'::jsonb,
	"tags" jsonb DEFAULT '[]'::jsonb,
	"title" text NOT NULL,
	"context" text NOT NULL,
	"goal" text NOT NULL,
	"constraints" jsonb NOT NULL,
	"example_input" text,
	"hints" jsonb NOT NULL,
	"rubric" jsonb NOT NULL,
	"passing_score" integer DEFAULT 70 NOT NULL,
	"ideal_response" text,
	"common_mistakes" jsonb DEFAULT '[]'::jsonb,
	"key_elements" jsonb DEFAULT '[]'::jsonb,
	"anti_patterns" jsonb DEFAULT '[]'::jsonb,
	"is_published" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
